### ISSUE TITLE
Functional and Non-Functional Requirements

### ISSUE THREAD

**Issue by Tole15** [BrightCoders-Institute/proyecto-final-oppenbarbies#2]
## Task
- [x] Identification and definition of the functional requirements of the prototype/MVP.
- [x] Identification and definition of the non-functional requirements of the prototype/MVP.
- [x] Prioritization of the requirements.
- [x] Documentation of the functional and non-functional requirements.
