### ISSUE TITLE
User Interface Design 

### ISSUE THREAD

**Issue by Tole15** [BrightCoders-Institute/proyecto-final-oppenbarbies#3]
## REQUIREMENTS / DESCRIPTION

- [x] Define the structure of the User Interface (UI).
- [x] Create low-fidelity prototypes using the graphic design tool:
 - Figma 

```[tasklist]
### Tasks Requeriments
- [x] Create low-fidelity prototypes using the graphic design tool: Figma
- [x] Define the structure of the User Interface (UI)
```
