### ISSUE TITLE
 Model of the Database

### ISSUE THREAD

**Issue by Tole15** [BrightCoders-Institute/proyecto-final-oppenbarbies#4]
## Tasks:

- [x] Identify the main entities and relationships of the system.
- [x] Design the conceptual model of the database using Entity-Relationship Diagrams (ERD).
- [x] Normalize the data model, if necessary.
- [x] Document the database model using dbdiagram.io or a similar tool.
- [x] Deliverable: Database Model Document. Integrate it into the README.md file of the repository through a link.
