### ISSUE TITLE
Presentation and Preparation for Coding

### ISSUE THREAD

**Issue by Tole15** [BrightCoders-Institute/proyecto-final-oppenbarbies#5]
## Tasks:

- [x] Present the proposal to mentors.
- [x] Plan the first work sprint.
- [x] Define the tasks to be performed.
- [x] Initiate the project.
