### ISSUE TITLE
Code Refactoring for Improved Maintainability

### ISSUE THREAD

**Issue by Eduardoespl** [BrightCoders-Institute/proyecto-final-oppenbarbies#52]
## REQUIREMENTS / DESCRIPTION

> The primary goal of this issue is to perform code refactoring, which involves restructuring and optimizing existing code to make it more organized, efficient, and understandable.

```[tasklist]
### Tasks
- [x] Code review and Analysis
- [x] Break down complex code
- [x] Remove duplicate code
- [x] Identify files, screens and components that need refactoring
```
