### ISSUE TITLE
Create View Available Time component

### ISSUE THREAD

**Issue by Eduardoespl** [BrightCoders-Institute/proyecto-final-oppenbarbies#54]
## REQUIREMENTS / DESCRIPTION

> A new component should be created from the provider's available times and displayed in a flatlist

```[tasklist]
### Tasks
- [ ] Create the component
- [ ] Get the data from the array of the available time from Details - Provider
- [ ] Show the data in a flatlist
```

## DESIGN

![image](https://github.com/BrightCoders-Institute/proyecto-final-oppenbarbies/assets/112664006/392e9560-7a72-438b-9feb-0162b80ced37)
