### ISSUE TITLE
Enhance Navbar Functionality

### ISSUE THREAD

**Issue by Eduardoespl** [BrightCoders-Institute/proyecto-final-oppenbarbies#55]
## REQUIREMENTS / DESCRIPTION

> The primary goal of this issue is to implement additional functionality and interactivity to the navbar, making navigation within the application more convenient and efficient.

```[tasklist]
### Tasks
- [x] Identify the screens that will use the navbar
- [x] Configure navigation between screens
- [x] The icon of the screen selected have to follow the style of the design
```

## DESIGN

![image](https://github.com/BrightCoders-Institute/proyecto-final-oppenbarbies/assets/112664006/55b0d0e0-7fda-490a-8fd2-d71651f109fd)
