### ISSUE TITLE
Configure Google Login Integration

### ISSUE THREAD

**Issue by Eduardoespl** [BrightCoders-Institute/proyecto-final-oppenbarbies#56]
## REQUIREMENTS / DESCRIPTION

> The primary goal of this issue is to integrate Google login into the application, allowing users to sign in using their Google credentials and enhancing the authentication options.

```[tasklist]
### Tasks
- [x] Setup the project
- [x] Add functionabily to Google Sign-In Button
- [x] Implement the logic with backend and front end
```
