### ISSUE TITLE
Create React Native Project using React Native CLI

### ISSUE THREAD

**Issue by DerekAyala** [BrightCoders-Institute/proyecto-final-oppenbarbies#6]
##  DESCRIPTION

This issue involves setting up a new React Native project using the React Native CLI. The project will serve as the foundation for the development of the mobile application. This issue encompasses the initial setup and configuration required to create the project.

```[tasklist]
### Tasks
- [x] Create a New React Native Project.
- [x] Verify Project Setup.
- [x] Basic Application Structure.
```
