### ISSUE TITLE
Implement Modal for Viewing Appointment Details

### ISSUE THREAD

**Issue by Eduardoespl** [BrightCoders-Institute/proyecto-final-oppenbarbies#60]
## REQUIREMENTS / DESCRIPTION

> The main goal of this issue is to design and implement a modal component that displays comprehensive details of an appointment when users interact with it.

```[tasklist]
### Tasks
- [x] Design Modal Layout
- [x] Implement the logic to trigger the modal display when a user clicks on an appointment item or a designated action.
- [x] Show the details of the selected appointment
```

## DESIGN

![image](https://github.com/BrightCoders-Institute/proyecto-final-oppenbarbies/assets/112664006/34eec45a-5894-4057-98c6-b650f5a3f432)
