### ISSUE TITLE
Create Arrow Back Component for Navigation

### ISSUE THREAD

**Issue by Eduardoespl** [BrightCoders-Institute/proyecto-final-oppenbarbies#68]
## REQUIREMENTS / DESCRIPTION

The main goal of this issue is to create a reusable "Arrow Back" component that enhances navigation by offering users a standardized method to go back within the application.

```[tasklist]
### Tasks
- [x] Create the new file for the component
- [x] Implement the logic to handle the click interaction of the "Arrow Back" component.
- [x] Ensure that clicking the component triggers the appropriate navigation action.
- [x] Use this component on the screens that requires it
```

## DESIGN

![image](https://github.com/BrightCoders-Institute/proyecto-final-oppenbarbies/assets/112664006/2a58dadf-b9a3-4b8a-842e-3d25014b3df1)
