### ISSUE TITLE
Implement Navigation to Provider Profile Page

### ISSUE THREAD

**Issue by DerekAyala** [BrightCoders-Institute/proyecto-final-oppenbarbies#88]
## DESCRIPTION
This issue involves enabling users to navigate from the list of service providers and search suggestions to the dedicated provider profile page when they select a provider.

```[tasklist]
### Tasks
- [ ] List Item Click Handling
- [ ] Search Suggestion Click Handling
- [ ] ofile Page Linking
```
